site_name: Lincoln Ombelets - ljo.bio 
site_url: http://ljo.bio/mkdocs
site_dir: public/mkdocs
theme: slate 

nav:
  - 'index.md'
  - 'reading.md'
  - 'about.md'
  - 'publications.md'
  - 'posts/2020-08-01-bio-future.md'
