site_name: Lincoln Ombelets - ljo.bio 
site_url: http://ljo.bio/
site_dir: public/

theme: 
  name: flatly 
  custom_dir: 'custom_theme/' 
  navigation_depth: 3
  include_sidebar: true

#plugins:
#  - blog


extra:
  posts_dir: 'posts/'
