site_name: Lincoln Ombelets - ljo.bio 
site_url: http://ljo.bio/
site_dir: public/
repo_url: https://github.com/lincdog/ljo-site
remote_branch: gh-pages
edit_uri: blob/main/docs/
remote_name: origin
site_author: Lincoln Ombelets

google_analytics: ['G-C04TMKNPL7', 'ljo.bio']

theme: 
  name: flatly 
  custom_dir: 'custom_theme/' 
  navigation_depth: 3
  include_sidebar: true

#plugins:
#  - blog

extra_css:
  - 'extra.css'

extra:
  posts_dir: 'posts/'
