site_name: Lincoln Ombelets - ljo.bio 
site_url: http://ljo.bio/
site_dir: public/
theme: 
  name: flatly
  custom_dir: 'custom_theme/' 

#nav:
#  - 'index.md'
#  - 'reading.md'
#  - 'about.md'
#  - 'publications.md'
#  - 2020/

#plugins:
#  - blog
