site_name: Lincoln Ombelets - ljo.bio 
site_url: http://ljo.bio/
site_dir: public/

google_analytics: ['G-C04TMKNPL7', 'ljo.bio']

theme: 
  name: flatly 
  custom_dir: 'custom_theme/' 
  navigation_depth: 3
  include_sidebar: true

#plugins:
#  - blog

extra_css:
  - 'extra.css'

extra:
  posts_dir: 'posts/'
